//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Project.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TestEntities : DbContext
    {
        public TestEntities()
            : base("name=TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STI> STI { get; set; }
        public virtual DbSet<STK> STK { get; set; }
    
        public virtual ObjectResult<TestProcedure_Result> TestProcedure(string malkodu, Nullable<int> baslangicTarihi, Nullable<int> bitisTarihi)
        {
            var malkoduParameter = malkodu != null ?
                new ObjectParameter("Malkodu", malkodu) :
                new ObjectParameter("Malkodu", typeof(string));
    
            var baslangicTarihiParameter = baslangicTarihi.HasValue ?
                new ObjectParameter("BaslangicTarihi", baslangicTarihi) :
                new ObjectParameter("BaslangicTarihi", typeof(int));
    
            var bitisTarihiParameter = bitisTarihi.HasValue ?
                new ObjectParameter("BitisTarihi", bitisTarihi) :
                new ObjectParameter("BitisTarihi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TestProcedure_Result>("TestProcedure", malkoduParameter, baslangicTarihiParameter, bitisTarihiParameter);
        }
    }
}
